name: Trivy Security Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  trivy:
    name: Trivy Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y

    - name: Run Trivy scan on filesystem
      run: |
        trivy fs --exit-code 1 --severity HIGH,CRITICAL --format json --output trivy-report.json .

    - name: Upload scan report (bonus)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy-report.json
